#!/usr/bin/env python3
"""Regenerate tools/README.md: one line per tool, taken from its own docstring or header comment, so an agent
can find the right tool without being told about each one in the guide. Run by the daily roundup.
  python3 tools/index.py [--check]      --check exits 1 when the file on disk is out of date
"""
import glob, os, re, sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..")); os.chdir(ROOT)


def purpose(path):
    s = open(path, errors="replace").read()
    m = re.search(r'^"""(.+?)(?:\n|""")', s, re.S | re.M) if path.endswith(".py") else None
    if m: return " ".join(m.group(1).split())
    for line in s.splitlines()[1:6]:                      # a shell script's header comment
        t = line.strip()
        if t.startswith("#") and len(t) > 3 and not t.startswith("#!"): return t.lstrip("# ").strip()
    return "(no description in the file)"


def build():
    rows = []
    for f in sorted(glob.glob("tools/*.py") + glob.glob("tools/*.sh")):
        if os.path.basename(f) in ("__init__.py",): continue
        rows.append("- `%s` — %s" % (f, purpose(f)))
    return ("# tools — what each one is for\n\n"
            "Generated by `python3 tools/index.py` from each tool's own first line; edit the tool, not this file.\n"
            "A worker's own loop is in AGENT_GUIDE.md; this is the index for everything else.\n\n" + "\n".join(rows) + "\n")


if __name__ == "__main__":
    doc = build(); path = "tools/README.md"
    old = open(path).read() if os.path.exists(path) else ""
    if "--check" in sys.argv:
        print("tools/README.md is %s" % ("current" if old == doc else "out of date")); sys.exit(0 if old == doc else 1)
    open(path, "w").write(doc); print("wrote %s (%d tools)%s" % (path, doc.count("\n- "), "" if old != doc else ", unchanged"))
