#!/usr/bin/env python3
"""The provider map (providers.toml) as a tool: renders the pi agent files, answers "which model for this
role on this provider", checks a provider's budget, and prints the coordinator instruction for a run.

  roles.py render                      write .pi/agents/<role>-<provider>.md for every provider and role
                                       template in .pi/roles/, plus bare <role>.md aliases for the first
                                       active provider (so an instruction may say "verifier" for short)
  roles.py model <provider> <role>     print the model id (e.g. hyper worker -> hyper/glm-5.3-flash)
  roles.py schedule                    shell lines: ACTIVE="hyper" PARALLEL=0 RESERVE="openrouter" WORKERS=2
  roles.py budget <provider> --start|--stop
                                       exit 0 when the provider can start a run / keep running, 1 when not,
                                       2 when the probe failed (never treated as exhausted)
  roles.py instruction <provider> [--workers N]
                                       the run instruction naming that provider's roles
  roles.py check                       validate the map; exit 1 with the reasons if it is inconsistent
  roles.py first                       the first active provider (what one-shot tools default to)
"""
import os, re, subprocess, sys, tomllib

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
ROLES = ("coordinator", "worker", "verifier", "recon", "judge", "auditor", "digest")
AGENT_ROLES = ("worker", "verifier", "recon")


def load():
    return tomllib.load(open(os.path.join(ROOT, "providers.toml"), "rb"))


def first(cfg):
    return cfg["schedule"]["active"][0]


def model(cfg, provider, role):
    try:
        return cfg["providers"][provider]["roles"][role]
    except KeyError:
        sys.exit("providers.toml: no model for role %r on provider %r" % (role, provider))


def render(cfg):
    out = os.path.join(ROOT, ".pi", "agents"); os.makedirs(out, exist_ok=True)
    written = []
    for prov in cfg["providers"]:
        for role in AGENT_ROLES:
            tpl = open(os.path.join(ROOT, ".pi", "roles", role + ".md")).read()
            fm, body = tpl.split("---\n", 2)[1], tpl.split("---\n", 2)[2]
            names = [role + "-" + prov] + ([role] if prov == first(cfg) else [])
            for name in names:
                head = "name: %s\n%s\nmodel: %s" % (name, fm.rstrip("\n"), model(cfg, prov, role))
                note = ("<!-- generated by tools/roles.py from providers.toml and .pi/roles/%s.md; edit those, not this -->\n"
                        % role)
                path = os.path.join(out, name + ".md")
                open(path, "w").write("---\n%s\n---\n%s%s" % (head, note, body))
                written.append(name)
    # generated files for providers no longer in the map
    for f in os.listdir(out):
        if f.endswith(".md") and f[:-3] not in written and "generated by tools/roles.py" in open(os.path.join(out, f)).read():
            os.remove(os.path.join(out, f)); print("removed stale", f)
    print("rendered:", " ".join(written))


def probe(cfg, provider):
    p = cfg["providers"][provider]
    r = subprocess.run(p["probe"], shell=True, capture_output=True, text=True, cwd=ROOT)
    return r.returncode, (r.stdout + r.stderr).strip().splitlines()[-1] if (r.stdout + r.stderr).strip() else ""


def budget(cfg, provider, phase):
    p = cfg["providers"][provider]
    if p["kind"] == "subscription":
        need = p["start_above"] if phase == "--start" else p["stop_below"]
        r = subprocess.run(p["probe"] + " --min %s" % need, shell=True, capture_output=True, text=True, cwd=ROOT)
        line = (r.stdout + r.stderr).strip().splitlines()[-1] if (r.stdout + r.stderr).strip() else ""
        print(line); return 0 if r.returncode == 0 else (1 if r.returncode == 1 else 2)
    rc, line = probe(cfg, provider); print(line)
    m = re.search(r"remaining \$([0-9.]+)", line)
    if rc not in (0, 1) or not m: return 2
    remaining = float(m.group(1)); floor = p.get("floor_usd", 0.0)
    need = floor + (p.get("start_above", 1.0) if phase == "--start" else 0.0)
    return 0 if remaining > need else 1


def instruction(cfg, provider, workers):
    p = cfg["providers"][provider]
    roles = ", ".join("%s-%s" % (r, provider) for r in AGENT_ROLES)
    if p["kind"] == "subscription":
        money = ("%s is a subscription with a daily balance the user wants spent to the end; the run stops by itself "
                 "when the balance is gone (a watcher outside you), so never stop for budget reasons." % provider)
    else:
        money = ("%s is pay as you go with a hard cap per run enforced outside you and a floor of $%.2f on the account; "
                 "never stop for budget reasons yourself." % (provider, p.get("floor_usd", 0.0)))
    return ("Run the loop with %d workers in flight. The roles for this run are %s: dispatch tickets to worker-%s, "
            "claims beyond harness lines to verifier-%s, code questions to recon-%s, and nothing to any other role. "
            "Use `python3 tools/next_ticket.py --pair %d --claim`. %s The phase is porting: the queue is whatever "
            "next_ticket.py returns until none is OPEN (then the judge refill in your instructions). Each landing keeps "
            "the full table identical (every isolated row 0; cursor's single-frame tear moves with the ROM layout and is "
            "reported, not chased), verified with tools/verify_rows.py and the trace as the tickets say; the verifier only "
            "when the branch merges and a claim needs it. Commits arriving on main from the human session or another "
            "provider's run are normal. No model overrides beyond the roles named."
            % (workers, roles, provider, provider, provider, workers, money))


def check(cfg):
    bad = []
    sched = cfg.get("schedule", {})
    for key in ("active", "parallel", "reserve", "workers"):
        if key not in sched: bad.append("schedule.%s missing" % key)
    for prov in sched.get("active", []) + sched.get("reserve", []):
        if prov not in cfg.get("providers", {}): bad.append("schedule names unknown provider %r" % prov)
    for prov, p in cfg.get("providers", {}).items():
        if p.get("kind") not in ("subscription", "payg"): bad.append("%s.kind must be subscription or payg" % prov)
        if "probe" not in p: bad.append("%s.probe missing" % prov)
        for role in ROLES:
            m = p.get("roles", {}).get(role)
            if not m: bad.append("%s.roles.%s missing" % (prov, role))
            elif "/" not in m: bad.append("%s.roles.%s = %r is not a pi model id (provider/model)" % (prov, role, m))
            elif not m.startswith(prov + "/"): print("note: %s.roles.%s borrows %s (its spend lands on that provider)" % (prov, role, m))
        if p["kind"] == "subscription" and not all(k in p for k in ("start_above", "stop_below")):
            bad.append("%s needs start_above and stop_below" % prov)
        if p["kind"] == "payg" and "floor_usd" not in p: bad.append("%s needs floor_usd" % prov)
    for role in AGENT_ROLES:
        if not os.path.exists(os.path.join(ROOT, ".pi", "roles", role + ".md")): bad.append(".pi/roles/%s.md missing" % role)
    if bad:
        print("\n".join("providers.toml: " + b for b in bad)); return 1
    print("providers.toml ok: active %s, parallel %s, reserve %s, %d workers" % (
        sched["active"], sched["parallel"], sched["reserve"], sched["workers"])); return 0


def main():
    a = sys.argv[1:]
    if not a: sys.exit(__doc__)
    cfg = load(); cmd = a[0]
    if cmd == "render": render(cfg)
    elif cmd == "model": print(model(cfg, a[1], a[2]))
    elif cmd == "first": print(first(cfg))
    elif cmd == "schedule":
        s = cfg["schedule"]
        print('ACTIVE="%s"\nPARALLEL=%d\nRESERVE="%s"\nWORKERS=%d' % (" ".join(s["active"]), 1 if s["parallel"] else 0, " ".join(s["reserve"]), s["workers"]))
    elif cmd == "budget": sys.exit(budget(cfg, a[1], a[2] if len(a) > 2 else "--start"))
    elif cmd == "instruction":
        n = int(a[a.index("--workers") + 1]) if "--workers" in a else cfg["schedule"]["workers"]
        print(instruction(cfg, a[1], n))
    elif cmd == "check": sys.exit(check(cfg))
    else: sys.exit("unknown command %r\n%s" % (cmd, __doc__))


if __name__ == "__main__":
    main()
